### ISSUE TITLE
Share this repo under https://github.com/linkedin-faq 

### ISSUE THREAD

**Issue by Ebazhanov** [IamGideonIdoko/linassess#4]
Hello, @IamGideonIdoko 

This web app looks great, can you share it under this organisation https://github.com/linkedin-faq
Just want to keep all related staff in one place. If yes let me know I will grand you edit access.

Best regards

**Comment by iamgideonidoko** [comment]
@Ebazhanov sure, I'd love to.

**Comment by Ebazhanov** [comment]
> @Ebazhanov sure, I'd love to.

cool i just sent request to you

**Comment by iamgideonidoko** [comment]
> cool i just sent request to you

I just forked this repo under the organization, linkedin-faq. Is it ok this way or should I completely move the project to linkedin-faq?

**Comment by Ebazhanov** [comment]
yes fork is fine, thanks
